version: 0.2  # Buildspecファイルのバージョン

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1  # AWSのデフォルトリージョン
    AWS_ACCOUNT_ID: 345850111772  # AWSアカウントID
    IMAGE_REPO_NAME: yolo12-test-ecr  # Dockerイメージのリポジトリ名
    IMAGE_TAG: latest  # Dockerイメージのタグ

phases:
  build:
    commands:
      # ECRにログイン
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      # Dockerイメージをビルド
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      
      # Dockerイメージにタグを付ける
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
      # DockerイメージをECRにプッシュ
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
      # imagedefinitions.jsonファイルを生成
      # 「"name":」にはECSのタスク定義で設定したコンテナ名を入れる
      - printf '[{"name":"yolo12-test-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json  # ビルド成果物としてimagedefinitions.jsonを指定